#include "Help.h"
#include <iostream>

bool Help::execute() {
  /*const char helpMessages<> =/
      "FILE COMMANDS:\n"
      " cd <path>                                   Change the current directory with path\n"
      " pwd                                         Print the current directory\n"
      " file <filePath>                             Create a new file in path\n"
      " del <filePath>                              Delete the file mentioned in path\n"
      " delreboot <filePath>                        Delete the file mentioned in path at reboot\n"
      " read <filePath> <position> <nrOfBytes> <-b> Read the <file> starts with <position> for a <nrOfBytes> of bites, optionally you can read binary by adding the optional flag \"-b\"\n"
      " write <filePath> <text> <position>          Write in <file> the <text> at optionally <position>\n"
      " dir <path> <-r>                             List the content of <path> and if the optional path <-r> is provided then it will list the content recursively.\n"
      " chm <filePath> <attributes>                 Set to <filePath> the <attributes>.\n"
      " cpy <filePath> <destionationPath>           Copy file to <destionationPath>.\n"
      " move <filePath> <destionationPath>          Move file to <destionationPath>\n"
      "REGISTRY COMMANDS:\n"
      " getKey <keyPath>                            List the subkeys and the values of <keyPath>.\n"
      " createKey <keyPath>                         Create <keyPath>.\n"
      " deleteKey <keyPath>                         Delete <keyPath>.\n"
      " createValue <keyPath> <valName> <valueType> Create <valName> of optionally <valueType> in <keyPath>.\n"
      " deleteValue <keyPath> <valueName>           Delete the <valueName>.\n"
      " setData <keyPath> <valueName> <valueData>   Set the <valueData> in <valueName> at <keyPath>.\n"
      " regDir <keyPath>                            List all values and subKeys of <keyPath> recursively.\n"
      "PROCESSES COMMANDS:\n"
      " createProc <exePath>                        Run the <exePath>.\n"
      " killProcs <PID> <-c>                        Kill the process with id <PID> and all its childs if flag \"-c\" is provided.\n"
      " suspendProc <PID> <-c>                      Suspend the process with id <PID> and all its childs if flag \"-c\" is provided.\n"
      " critProc <PID>                              Critic. the process with id <PID>\n"
      " unCritProc <PID>                            Uncritic. the process with id <PID>\n";*/
  tstring msg =  _T("FILE COMMANDS:\n"
      " cd <path>                                   Change the current directory with path\n"
      " pwd                                         Print the current directory\n"
      " file <filePath>                             Create a new file in path\n"
      " del <filePath>                              Delete the file mentioned in path\n"
      " delreboot <filePath>                        Delete the file mentioned in path at reboot\n"
      " read <filePath> <position> <nrOfBytes> [-b] Read the <file> starts with <position> for a <nrOfBytes> of bites, optionally you can read binary by adding the optional flag \"-b\"\n"
      " write <filePath> <text> [position]          Write in <file> the <text> at optionally <position>\n"
      " dir <path> [-r]                             List the content of <path> and if the optional flag \"-r\" is provided then it will list the content recursively.\n"
      " chm <filePath> <attributes>                 Set to <filePath> the <attributes>.\n"
      " cpy <filePath> <destionationPath>           Copy file to <destionationPath>.\n"
      " move <filePath> <destionationPath>          Move file to <destionationPath>\n"
      "REGISTRY COMMANDS:\n"
      " getKey <keyPath>                            List the subkeys and the values of <keyPath>.\n"
      " createKey <keyPath>                         Create <keyPath>.\n"
      " deleteKey <keyPath>                         Delete <keyPath>.\n"
      " createValue <keyPath> <valName> <valueType> [valueData] Create <valName> of <valueType> in <keyPath> with optionally [valueData].\n"
      " deleteValue <keyPath> <valueName>           Delete the <valueName>.\n"
      " setData <keyPath> <valueName> <valueData>   Set the <valueData> in <valueName> at <keyPath>.\n"
      " regDir <keyPath>                            List all values and subKeys of <keyPath> recursively.\n"
      "PROCESSES COMMANDS:\n"
      " createProc <exePath>                        Run the <exePath>.\n"
      " killProcs <PID> [-c]                        Kill the process with id <PID> and all its childs if optionally flag \"-c\" is provided\n"
      " suspendProc <PID> [-c]                      Suspend the process with id <PID> and all its childs if optionally flag \"-c\" is provided.\n"
      " critProc <PID>                              Critic. the process with id <PID>.\n"
      " unCritProc <PID>                            Uncritic. the process with id <PID>.\n");

  Server::AddCommandInString(msg);
  return true;
}
